# -*- coding: utf-8 -*-
"""calculadora_basica_mi_primer_proyecto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UkpzP69wcFdCUwgP764TOHdT4hWKocB6

#En este notebook comenzaré a desarrollar una calculadora por diversion con el solo fin de aprender.

> Utilizaré tutoriales y otras erramientas que puedan ayudarme. La finalidad de este proyecto es relacionarme con el codigo, aprender y aplicar las pequeñas cosas que he aprendido hasta ahora.
"""

# Calculadora basica.

def menu():
  print("Bienvenido a la Calculadora\
 Básica".center(63, "-"))
  print("*" * 63)
  print("A continuación elige una de las\
 siguientes operaciones".center(63, "-"))
  print("1. Suma ", " 2. Resta ", " 3. Multiplicación ",\
        " 4. División ", " 5. Salir", sep="|")

def calculadora():
  while True:
    menu()
    print(" " * 63)
    try:
      opcion = int(input("Selecciona una opción: "))
    except ValueError:
      print(" " * 63)
      print("Por favor ingresa una opción válida".center(63, "-"))
      print(" " * 63)
      continue
    print(" " * 63)
    if opcion == 5:
      print("Gracias por utilizar la calculadora básica".center(63, "-"))
      break

    try:
      num1 = float(input("Ingresa el primer número: "))
      num2 = float(input("Ingresa el segundo número: "))
      print(" " * 63)
    except ValueError:
      print("Por favor ingresa un número".center(63, "-"))
      print(" " * 63)
      continue

    if opcion == 1:
      print(f"El resultado de la suma es: {num1 + num2}".center(63, "-"))
      print(" " * 63)
    elif opcion == 2:
      print(f"El resultado de la resta es: {num1 - num2}".center(63, "-"))
      print(" " * 63)
    elif opcion == 3:
      print(f"El resultado de la multiplicación es: {num1 * num2}".center(63, "-"))
      print(" " * 63)
    elif opcion == 4:
      if num2 == 0:
        print("No se puede dividir entre cero".center(63, "-"))
        print(" " * 63)
      else:
        print(f"El resultado de la división es: {num1 / num2}".center(63, "-"))
        print(" " * 63)
    else:
      print("Opción no válida".center(63, "-"))

calculadora()